title: Premkumar Masilamani
tagline: Software Architect - Writer - Life Coach

home-page-url: https://www.smileprem.com
software-architect-url: https://www.linkedin.com/in/premkumarmasilamani
english-blog-url: https://blog.smileprem.com
tamil-blog-url: https://tamil.smileprem.com
life-coach-url: https://cal.com/coachprem/chemistry-session
twitter-url: https://twitter.com/PremMasilamani

copyright: copyleft @ 2009.

include:
  - "_pages"

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 1000

permalink: /:title/
